// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_aboutdialog.cpp"
#include "EWIEGA46WW/moc_capturesettingsdialog.cpp"
#include "EWIEGA46WW/moc_closedialog.cpp"
#include "EWIEGA46WW/moc_globalhotkeymanager.cpp"
#include "EWIEGA46WW/moc_longcapturesessioncontroller.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_selectionoverlay.cpp"
#include "EWIEGA46WW/moc_showtip.cpp"
